import json
import os
import time

import pytest

from jarvis import claude_sessions as cs
from jarvis import paths
from claude_fixtures import A, T, U, home, make, proj  # noqa: F401
from jarvis.claude_sessions import Ranked, Session


# ---- parsing --------------------------------------------------------------------------------------------
def test_parse_mixed_formats(home):
    p = proj(home, "code", "Jarvis")
    f = make(home, p, "s1", [
        {"type": "summary", "summary": "Old summary", "leafUuid": "x"},
        "garbage {{{",
        "",
        "[1, 2]",
        U("<command-name>/clear</command-name>", cwd=str(p)),
        U("Caveat: The messages below were generated by the user", cwd=str(p)),
        U("meta noise", isMeta=True),
        U("side chat", isSidechain=True),
        U([{"type": "text", "text": "fix the login bug please"}], cwd=str(p), ts="2026-10-01T10:00:00Z"),
        A([{"type": "thinking", "thinking": "hmm"}]),
        A([T("Looking at auth."), {"type": "tool_use", "name": "Read", "input": {}}]),
        {"type": "user", "message": {"content": [{"type": "tool_result", "content": "file data"}]}},
        A([{"type": "tool_use", "name": "Edit", "input": {}}]),
        A([T("Fixed **it**. All good.")]),
        {"type": "custom-title", "customTitle": "Login bug"},
    ])
    s = cs.parse_session(f)
    assert s.id == "s1" and s.project_dir == str(p) and s.project_name == "Jarvis"
    assert s.title == "Login bug"  # custom title beats summary
    assert s.first_message == "fix the login bug please"
    assert s.last_assistant_text.startswith("Fixed **it**")
    assert s.last_tool == "Edit"
    assert s.last_kind == "assistant_text"
    assert s.message_count == 4  # user + 3 assistant with content; meta/sidechain/noise/tool_result skipped
    assert s.last_user_ts == pytest.approx(1790848800.0, abs=1)
    assert s.last_activity == os.stat(f).st_mtime


def test_parse_title_fallbacks_and_decoded_dir(home):
    f = make(home, "C:\\Users\\Nik\\proj", "s2", [U("hello there"), A([T("hi")])])
    s = cs.parse_session(f)
    assert s.title == "" and s.label == "hello there"
    assert s.project_dir == "C:\\Users\\Nik\\proj" and s.project_name == "proj"
    assert cs.decode_project("C--Users-Nik-proj") == "C:\\Users\\Nik\\proj"
    assert cs.decode_project("-home-nik-proj") == "/home/nik/proj"
    f2 = make(home, "/x/y", "s3", [{"type": "summary", "summary": "Summary title"}, U("q", cwd="/x/y")])
    assert cs.parse_session(f2).title == "Summary title"
    f3 = make(home, "/x/z", "s4", [{"type": "ai-title", "aiTitle": "AI title"}, {"type": "summary", "summary": "S"},
                                    U("q", cwd="/x/z")])
    assert cs.parse_session(f3).title == "AI title"


def test_parse_empty_and_garbage_only_returns_none(home):
    assert cs.parse_session(make(home, "/a", "e1", ["nope", "{bad"])) is None
    assert cs.parse_session(make(home, "/a", "e2", [U("x", isMeta=True)])) is None
    assert cs.parse_session(home / "missing.jsonl") is None


def test_large_file_reads_head_and_tail_only(home):
    p = proj(home, "big")
    filler = [A([T("filler " * 200)]) for _ in range(800)]  # > 300 KB
    f = make(home, p, "big1", [U("the very first request", cwd=str(p))] + filler +
             [U("last request"), A([T("final answer here.")])])
    assert f.stat().st_size > cs.HEAD_BYTES + cs.TAIL_BYTES
    s = cs.parse_session(f)
    assert s.first_message == "the very first request"
    assert s.last_assistant_text == "final answer here."
    assert s.message_count >= 800


def test_cache_by_mtime_and_size(home, monkeypatch):
    p = proj(home, "c")
    f = make(home, p, "c1", [U("one", cwd=str(p)), A([T("a")])], mtime=1_000_000)
    calls = []
    real = cs.parse_session
    monkeypatch.setattr(cs, "parse_session", lambda *a, **k: (calls.append(1), real(*a, **k))[1])
    cs.load_session(f)
    cs.load_session(f)
    assert len(calls) == 1
    with f.open("a") as fh:
        fh.write(json.dumps(A([T("more")])) + "\n")
    cs.load_session(f)
    assert len(calls) == 2


def test_scan_sessions_newest_first(home):
    a, b = proj(home, "a"), proj(home, "b")
    now = time.time()
    make(home, a, "old", [U("old", cwd=str(a))], now - 5000)
    make(home, b, "new", [U("new", cwd=str(b))], now - 10)
    assert [s.id for s in cs.scan_sessions()] == ["new", "old"]


# ---- humanize / formatting -----------------------------------------------------------------------------------
@pytest.mark.parametrize("secs,text", [
    (5, "just now"), (60, "1 minute ago"), (300, "5 minutes ago"), (3600, "1 hour ago"), (7300, "2 hours ago"),
    (86400, "yesterday"), (3 * 86400, "3 days ago"), (21 * 86400, "3 weeks ago"), (90 * 86400, "3 months ago"),
])
def test_humanize_age(secs, text):
    assert cs.humanize_age(secs) == text


def mk(id, title, first="", project="/p/Jarvis", age=3600, **kw):
    now = 1_800_000_000.0
    return Session(id=id, path="", project_dir=project, project_name=cs.basename(project), title=title,
                   first_message=first, last_activity=now - age, **kw)


def test_spoken_list_formatting():
    now = 1_800_000_000.0
    s = [mk("1", "Login bug", age=7300), mk("2", "", first="add dark mode to the settings page " * 5, project="/p/Site", age=86400)]
    out = cs.format_list(s, now)
    lines = out.splitlines()
    assert lines[0] == "1. Login bug, Jarvis, 2 hours ago"
    assert lines[1].startswith("2. add dark mode to the settings page") and lines[1].endswith(", Site, yesterday")
    assert "..." in lines[1]


def test_first_sentences_and_speakable():
    t = "**Done.** I fixed `auth.py`. Then I ran tests. They pass.\n```py\ncode\n```"
    assert cs.first_sentences(t, 2) == "Done. I fixed auth.py."
    assert cs.first_sentences("one two three four five six", 1, 3) == "one two three..."
    assert cs.first_sentences("") == ""


# ---- projects --------------------------------------------------------------------------------------------------
def build_projects(home):
    jarvis = proj(home, "Documents", "Ai on pc", "Jarvis")
    site = proj(home, "Desktop", "my-site")
    other = proj(home, "code", "VideoTest")
    proj(home, "Documents", "Taxes 2025")
    now = time.time()
    make(home, jarvis, "j1", [U("fix the login bug", cwd=str(jarvis)), A([T("Fixed.")])], now - 7200)
    make(home, other, "v1", [U("render the video", cwd=str(other)), A([T("ok")])], now - 100)
    return jarvis, site, other


def test_projects_from_history_and_known_folders(home):
    jarvis, site, other = build_projects(home)
    got = cs.projects()
    assert str(jarvis) in got and str(other) in got
    assert str(site) in got  # Desktop subfolder without sessions
    assert str(home / "Documents" / "Taxes 2025") in got
    assert str(home / "Documents") not in got and str(home / "Desktop") not in got
    assert len(got) == len(set(got))


@pytest.mark.parametrize("spoken", [
    "jarvis", "Jarvis", "the jarvis project", "jarvis project folder", "ai on pc", "jarvis pc assistant", "Jarvs",
])
def test_resolve_project_jarvis(home, spoken):
    jarvis, *_ = build_projects(home)
    assert cs.resolve_project(spoken) == str(jarvis)


def test_resolve_project_others(home):
    jarvis, site, other = build_projects(home)
    assert cs.resolve_project("video test") == str(other)
    assert cs.resolve_project("videotest") == str(other)
    assert cs.resolve_project("my site") == str(site)
    assert cs.resolve_project("taxes") == str(home / "Documents" / "Taxes 2025")
    assert cs.resolve_project("quantum fridge") is None
    assert cs.resolve_project("") is None
    assert cs.resolve_project("the project") is None
    assert cs.resolve_project(str(other)) == str(other)


# ---- ranking -------------------------------------------------------------------------------------------------------
def test_find_sessions_ranks_by_topic_and_project():
    S = [mk("a", "Login bug", age=86400 * 2), mk("b", "Dark mode", age=60),
         mk("c", "", first="login page is broken", project="/p/Site", age=100)]
    now = 1_800_000_000.0
    r = cs.find_sessions("login bug", sessions=S, now=now)
    assert [x.session.id for x in r] == ["a", "c"]
    assert not cs.is_ambiguous(r)
    r = cs.find_sessions("login", project=None, sessions=S, now=now)
    assert r[0].session.id == "a"
    assert cs.find_sessions("quantum", sessions=S, now=now) == []


def test_find_sessions_project_filter_and_empty_query_is_recency(home):
    jarvis, site, other = build_projects(home)
    r = cs.find_sessions("", sessions=cs.scan_sessions())
    assert [x.session.id for x in r] == ["v1", "j1"]
    r = cs.find_sessions("", project="jarvis", sessions=cs.scan_sessions())
    assert [x.session.id for x in r] == ["j1"]
    assert cs.find_sessions("", project="no such project", sessions=cs.scan_sessions()) == []


def test_ambiguity_when_scores_close():
    now = 1_800_000_000.0
    S = [mk("a", "Login bug", age=3600), mk("b", "Login bug fix", age=7200), mk("c", "Unrelated", age=10)]
    r = cs.find_sessions("login bug", sessions=S, now=now)
    assert [x.session.id for x in r][:2] == ["a", "b"]
    assert cs.is_ambiguous(r)
    assert not cs.is_ambiguous([])
    assert not cs.is_ambiguous([Ranked(S[0], 1.0)])
    assert not cs.is_ambiguous([Ranked(S[0], 1.0), Ranked(S[1], 0.5)])


def test_looks_busy():
    now = 1_800_000_000.0
    assert cs.looks_busy(mk("a", "x", age=5, last_kind="tool_use"), now)
    assert not cs.looks_busy(mk("a", "x", age=5, last_kind="assistant_text"), now)
    assert not cs.looks_busy(mk("a", "x", age=60, last_kind="tool_use"), now)


def test_turn_seconds(home):
    p = proj(home, "t")
    f = make(home, p, "t1", [U("go", cwd=str(p), ts="2026-10-01T10:00:00Z"), A([T("done")])])
    base = cs.parse_session(f).last_user_ts
    assert cs.turn_seconds(str(f), now=base + 90) == pytest.approx(90)
    g = make(home, p, "t2", [U("go", cwd=str(p)), A([T("done")])])
    assert cs.turn_seconds(str(g)) is None
    assert cs.turn_seconds("") is None
